version: '3.9'
services:
  quiz-service-test:
    container_name: ${CONTAINER_NAME}
    image: registry.sheba.xyz/${CONTAINER_NAME}
    env_file: ../../.env.testing
    build:
      context: ../
      dockerfile: Dockerfile
    environment:
      SERVICE_NAME: app
    working_dir: /var/www
    entrypoint: /etc/entrypoint.sh
    volumes:
      - ../../:/var/www
      - ../supervisor/conf.d/horizon.conf:/etc/supervisor/conf.d/horizon.conf
      - ../nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf
      - ../nginx/conf.d/nginx-local.conf:/etc/nginx/sites-enabled/default
      - ../php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ../php/memory_limit.ini:/usr/local/etc/php/conf.d/memory_limit.ini
      - ../php/php.ini:/usr/local/etc/php/conf.d/php.override.ini
      - ../php/conf.d/www.local.conf:/usr/local/etc/php-fpm.d/www.conf
      - ../nginx/logs:/var/log/nginx
    ports:
      - ${PORT}:80
    extra_hosts:
      - "${VIRTUAL_HOST_DOCKER_HOST}:${DOCKER_HOST_ADDR}"
      - "${VIRTUAL_HOST_LOCALHOST}:${DOCKER_HOST_ADDR}"
    networks:
      - quiz-service-network

networks:
  quiz-service-network:
    name: ${EXTERNAL_NETWORK}
